### ISSUE TITLE
ModuleNotFoundError: No module named 'collectors'

### ISSUE THREAD

**Issue by DrorDvash** [login-securite/DonPAPI#104]
Hi, when donpapi is installed like so `pipx install git+https://github.com/login-securite/DonPAPI.git` i get the following error:

```
# donpapi collect -u user -p pass -d domain.com --dc-ip 10.10.10.10 --pvkfile pvkfile.pvk --target SRV01.domain.com
[💀] [+] DonPAPI Version 2.0.1
[💀] [+] Output directory at /root/.donpapi
Traceback (most recent call last):
  File "/root/.local/bin/donpapi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/share/pipx/venvs/donpapi/lib/python3.12/site-packages/donpapi/entry.py", line 333, in main
    _, collectors = load_collectors(root, options.collectors.split(","))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/donpapi/lib/python3.12/site-packages/donpapi/entry.py", line 59, in load_collectors
    loaded_collectors.append(getattr(import_module(f"collectors.{collector_name}"), collector_name))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'collectors'
```

when doing `pipx uninstall donpapi` and `pipx install donpapi` everything works fine.

Also, a general question please: when using `--fetch-pvk`, where donpapi saves the .pvk file?

Thanks

**Comment by 8BitLogic** [comment]
Hi. 
Try fixing the code as in my PR #105

**Comment by DrorDvash** [comment]
I asked GPT about the issue, he suggested to add:
sys.path.insert(0, root) in the entry.py main() function and this will do the job also.

![image](https://github.com/user-attachments/assets/7b86e5db-eff3-4938-9e8c-98a978ac6fb4)

thanks to @8BitLogic for his PR https://github.com/login-securite/DonPAPI/pull/105
