### ISSUE TITLE
Error when using --GetHashes 

### ISSUE THREAD

**Issue by corsch** [login-securite/DonPAPI#2]
When running DonPAPI with "--GetHashes" I get the following error.

```
Traceback (most recent call last):
  File "/<mytoolspath>/DonPAPI/DonPAPI.py", line 273, in <module>
    main()
  File "/<mytoolspath>/DonPAPI/DonPAPI.py", line 185, in main
    my_report.export_hashes()
AttributeError: 'reporting' object has no attribute 'export_hashes'
```

DonPAPI is running on KALI 2021.4 with Impacket v0.9.24.dev1+20210720.100427.cd4fe47c.
The target is Windows 10 1803

**Comment by login-securite** [comment]
Thanks for reporting this. It's now fixed!
