### ISSUE TITLE
[bug] ImportError: cannot import name 'PrivateKeyTypes' from 'cryptography.hazmat.primitives.asymmetric.types'

### ISSUE THREAD

**Issue by p0dalirius** [login-securite/DonPAPI#57]
Hi,

Upon installation with the commands on the README.md, we get an error when starting DonPAPI

```
root@podaliriuslab:~/DonPAPI# git clone https://github.com/login-securite/DonPAPI.git
Cloning into 'DonPAPI'...
remote: Enumerating objects: 787, done.
remote: Counting objects: 100% (381/381), done.
remote: Compressing objects: 100% (255/255), done.
remote: Total 787 (delta 166), reused 306 (delta 123), pack-reused 406
Receiving objects: 100% (787/787), 3.22 MiB | 26.34 MiB/s, done.
Resolving deltas: 100% (316/316), done.
Processing /root/DonPAPI/DonPAPI
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: LnkParse3<2.0.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from donpapi==1.1.0) (1.2.0)
Requirement already satisfied: M2Crypto<0.39.0,>=0.38.0 in /usr/local/lib/python3.11/dist-packages (from donpapi==1.1.0) (0.38.0)
Requirement already satisfied: impacket<0.10.0,>=0.9.23 in /usr/local/lib/python3.11/dist-packages (from donpapi==1.1.0) (0.9.24)
Requirement already satisfied: pyasn<2.0.0,>=1.6.1 in /usr/local/lib/python3.11/dist-packages (from donpapi==1.1.0) (1.6.1)
Requirement already satisfied: pycryptodome<4.0.0,>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from donpapi==1.1.0) (3.18.0)
Requirement already satisfied: swig<5.0.0,>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from donpapi==1.1.0) (4.1.1)
Requirement already satisfied: wheel<0.38.0,>=0.37.0 in /usr/local/lib/python3.11/dist-packages (from donpapi==1.1.0) (0.37.1)
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from impacket<0.10.0,>=0.9.23->donpapi==1.1.0) (5.1.0)
Requirement already satisfied: flask>=1.0 in /usr/lib/python3/dist-packages (from impacket<0.10.0,>=0.9.23->donpapi==1.1.0) (2.2.2)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from impacket<0.10.0,>=0.9.23->donpapi==1.1.0) (0.18.2)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /usr/lib/python3/dist-packages (from impacket<0.10.0,>=0.9.23->donpapi==1.1.0) (2.9.1)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /usr/lib/python3/dist-packages (from impacket<0.10.0,>=0.9.23->donpapi==1.1.0) (0.9.3)
Requirement already satisfied: pyOpenSSL>=0.16.2 in /usr/lib/python3/dist-packages (from impacket<0.10.0,>=0.9.23->donpapi==1.1.0) (23.0.0)
Requirement already satisfied: pyasn1>=0.2.3 in /usr/lib/python3/dist-packages (from impacket<0.10.0,>=0.9.23->donpapi==1.1.0) (0.4.8)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from impacket<0.10.0,>=0.9.23->donpapi==1.1.0) (3.11.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from impacket<0.10.0,>=0.9.23->donpapi==1.1.0) (1.16.0)
Building wheels for collected packages: donpapi
  Building wheel for donpapi (pyproject.toml) ... done
  Created wheel for donpapi: filename=donpapi-1.1.0-py3-none-any.whl size=692882 sha256=b90fce1ca309727c68f25d3c073f6332b9934f6b2d02ebbb185fbe70961a93eb
  Stored in directory: /tmp/pip-ephem-wheel-cache-_fzseqmg/wheels/f5/5d/af/daefae7c43f57686945d3ccdef02147a13c26bf4f09d46030f
Successfully built donpapi
Installing collected packages: donpapi
  Attempting uninstall: donpapi
    Found existing installation: donpapi 1.1.0
    Uninstalling donpapi-1.1.0:
      Successfully uninstalled donpapi-1.1.0
Successfully installed donpapi-1.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

root@podaliriuslab:~/DonPAPI# cd DonPAPI; python3 -m pip install . ; DonPAPI
Traceback (most recent call last):
  File "/usr/local/bin/DonPAPI", line 5, in <module>
    from donpapi.entry import main
  File "/usr/local/lib/python3.11/dist-packages/donpapi/entry.py", line 26, in <module>
    from donpapi.myseatbelt import MySeatBelt
  File "/usr/local/lib/python3.11/dist-packages/donpapi/myseatbelt.py", line 11, in <module>
    from donpapi.lib.certificates import CertificatesTriage
  File "/usr/local/lib/python3.11/dist-packages/donpapi/lib/certificates.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric.types import PrivateKeyTypes
ImportError: cannot import name 'PrivateKeyTypes' from 'cryptography.hazmat.primitives.asymmetric.types' (/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/asymmetric/types.py)                                                                                                                                                                                    
```

After a bit of research, this is because [cryptography=3.4] has a circular import bug, to fix it you should update to [cryptography=3.4.1].

For anyone having the bug now, you can just do:

```
root@podaliriuslab:~/DonPAPI# python3 -m pip install cryptography --upgrade
Requirement already satisfied: cryptography in /usr/local/lib/python3.11/dist-packages (3.4.8)
Collecting cryptography
  Using cached cryptography-41.0.2-cp37-abi3-manylinux_2_28_x86_64.whl (4.3 MB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography) (2.21)
Installing collected packages: cryptography
  Attempting uninstall: cryptography
    Found existing installation: cryptography 3.4.8
    Uninstalling cryptography-3.4.8:
      Successfully uninstalled cryptography-3.4.8
Successfully installed cryptography-41.0.2
```

More infos about the bug: https://cryptography.io/en/latest/changelog/#v3-4-1

**Comment by 7MinSec** [comment]
Just wanted to chime in and THANK YOU for these notes and a fix.  I desperately needed this tool on a pentest and your `python -m pip install cryptography --upgrade` did just the trick!

**Comment by p0dalirius** [comment]
Glad it helped!

**Comment by zblurx** [comment]
Thank you @p0dalirius , just merged your fix!

**Comment by zblurx** [comment]
It causes dependency problems so I revert the PR, gonna work on it

**Comment by zblurx** [comment]
Which python version are you using ? Did you installed DonPAPI on a separated virtualenv ?

**Comment by p0dalirius** [comment]
No I was working on a latest Kali without virtualenv. I'll give you more informations in a few days, I can't right now

**Comment by p0dalirius** [comment]
Here is the complete steps on a Kali machine:

I have installed DonPAPI like this:
![image](https://github.com/login-securite/DonPAPI/assets/79218792/0bd8f634-7e75-479b-b3ca-211e5a686c88)

This results in a badass traceback:
![image](https://github.com/login-securite/DonPAPI/assets/79218792/5ddfd16c-13a0-4f78-bf0c-17ae0122c47a)
![image](https://github.com/login-securite/DonPAPI/assets/79218792/6243463b-d395-4943-9f26-8ae83afe40c7)
![image](https://github.com/login-securite/DonPAPI/assets/79218792/395b9014-4c99-4745-aafc-51395cd3d0f6)
![image](https://github.com/login-securite/DonPAPI/assets/79218792/828ce0c1-f38c-4151-ae89-83bb2fafbbfd)

If i reinstall it just after this traceback the error does not reappear:

But DonPAPI still fails with the circular import bug in cryptography
![image](https://github.com/login-securite/DonPAPI/assets/79218792/7cc4ec84-04b9-45a6-8bba-8f1725fa24f6)

That is why I tried to add a newer version of cryptography in order to skip the affected version.

After running `python3 -m pip install cryptography --upgrade` I have the following packages and versions:

**Comment by zblurx** [comment]
I've just updated dependencies in the project. Can you recheck ? Also, please always install python tools in dedicated virtualenv, with pipx for example

**Comment by zblurx** [comment]
closing now. feel free to reopen if this appends again
