### ISSUE TITLE
Traceback crypto import error

### ISSUE THREAD

**Issue by ShutdownRepo** [login-securite/DonPAPI#59]
Traceback when running DonPAPI, probably due to latest commits

```
Traceback (most recent call last):
      File "/root/.local/bin/DonPAPI", line 5, in <module>
        from donpapi.entry import main
      File "/root/.local/pipx/venvs/donpapi/lib/python3.9/site-packages/donpapi/entry.py", line 26, in <module>
        from donpapi.myseatbelt import MySeatBelt
      File "/root/.local/pipx/venvs/donpapi/lib/python3.9/site-packages/donpapi/myseatbelt.py", line 11, in <module>
        from donpapi.lib.certificates import CertificatesTriage
      File "/root/.local/pipx/venvs/donpapi/lib/python3.9/site-packages/donpapi/lib/certificates.py", line 11, in <module>
        from cryptography.hazmat._oid import ExtensionOID
    ImportError: cannot import name 'ExtensionOID' from 'cryptography.hazmat._oid' (/root/.local/pipx/venvs/donpapi/lib/python3.9/site-packages/cryptography/hazmat/_oid.py)
```

**Comment by zblurx** [comment]
Hey, i reverted #58, so it should work now

**Comment by ShutdownRepo** [comment]
Confirmed
It was spotted by Exegol’s CI/CD pipeline, I guess you can call that pipeline-as-a-service 😂
